### ISSUE TITLE
Why Runbot is not working in this repository?

### ISSUE THREAD

**Issue by MiquelRForgeFlow** [OCA/project-reporting#15]
@gurneyalex

**Comment by MiquelRForgeFlow** [comment]
any news on this? @gurneyalex @moylop260

**Comment by moylop260** [comment]
A build requires a `TESTS=1` environment variable in the `.travis.yml`

Try using the latest version from template:
 - https://github.com/OCA/maintainer-quality-tools/blob/master/sample_files/.travis.yml

**Comment by MiquelRForgeFlow** [comment]
I tried in https://github.com/OCA/project-reporting/pull/30. Now runbot works fine. Still travis fails for unknown reason.
