### ISSUE TITLE
Create 8.0 branch and make it the default

### ISSUE THREAD

**Issue by dreispt** [OCA/project-reporting#2]

**Comment by yvaucher** [comment]
cc @jgrandguillaume @elicoidal @StefanRijnhart @max3903 @nhomar @sebastienbeau @gurneyalex

**Comment by dreispt** [comment]
And add dotfiles...

**Comment by yvaucher** [comment]
dotfiles and creating branches can be done by any commiter but not changing default

**Comment by StefanRijnhart** [comment]
Created 8.0 with existing modules in **unported**, set to default and removed master branch.

**Comment by yvaucher** [comment]
Thanks @StefanRijnhart
