### ISSUE TITLE
Merge with project-service

### ISSUE THREAD

**Issue by dreispt** [OCA/project-reporting#3]
This repo has only two modules in 7.0, none yet ported to 8.0.
AFAICS it's not "deep" enough to deserve it's own repository.

I propose to merge this with the [project-service](https://github.com/OCA/project-service) repository.

**Comment by rafaelbn** [comment]
@dreispt I think we can close this issue as discussed in https://github.com/OCA/project-reporting/issues/9 this repository will containing more modules in v8 than in v9
More over with the functionality in project service for services companies, for sure we will need more reporting.
So maybe now you think different with this proposal.

**Comment by dreispt** [comment]
Closing.
